WAFF.WebUI/Models/Block.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WAFF.WebUI.Models
{
    public class Block
    {
        public int BlockID { get; set; }
        public DateTime BlockStart { get; set; }
        public DateTime BlockEnd { get; set; }
        public string BlockLocation { get; set; }
        public string BlockType { get; set; }
        public int EventID { get; set; }

    }
}

WAFF.WebUI/Models/Blocks.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WAFF.WebUI.Models
{
    public class Blocks
    {
        public int BlockID { get; set; }
        public DateTime BlockStart { get; set; }
        public DateTime BlockEnd { get; set; }
        public string BlockLocation { get; set; }
        public string BlockType { get; set; }
        public int EventID { get; set; }

    }
}

WAFF.WebUI/Controllers/BlocksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WAFF.DataAccess.Contexts;
using WAFF.DataAccess.Entity;

namespace WAFF.WebUI.Controllers
{
    [Authorize]
    public class BlocksController : Controller
    {
        private EFDbContext db = new EFDbContext();

        // GET: Blocks
        public ActionResult Index()
        {
            return View(db.Blocks.ToList());
        }

        // GET: Blocks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Blocks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BlockID,BlockStart,BlockEnd,BlockLocation,BlockType,EventID")] Block block)
        {
            if (ModelState.IsValid)
            {
                db.Blocks.Add(block);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(block);
        }

        // GET: Blocks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Block block = db.Blocks.Find(id);
            if (block == null)
            {
                return HttpNotFound();
            }
            return View(block);
        }

        // POST: Blocks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BlockID,BlockStart,BlockEnd,BlockLocation,BlockType,EventID")] Block block)
        {
            if (ModelState.IsValid)
            {
                db.Entry(block).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(block);
        }

        // GET: Blocks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Block block = db.Blocks.Find(id);
            if (block == null)
            {
                return HttpNotFound();
            }
            return View(block);
        }

        // POST: Blocks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            IEnumerable<FilmBlock> fb = db.FilmBlocks.Where(x => x.BlockID == id);
            db.FilmBlocks.RemoveRange(fb);

            db.SaveChanges();
            
            Block block = db.Blocks.Find(id);
            db.Blocks.Remove(block);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WAFF.WebUI/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WAFF.Services.Reports;
using WAFF.WebUI.Models;
using WAFF.DataAccess.ViewModels;

namespace WAFF.WebUI.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        // Create a ReportsService object to get information for Leaderboards
        ReportService _service = new ReportService();

        public ActionResult VotingData()
        {
            var events = _service.GetEvents();

            return View(events);
        }

        public PartialViewResult EventSelect()
        {
            var events = _service.GetEvents();

            return PartialView(events);
        }

        public PartialViewResult EventLB()
        {
            var events = _service.GetEvents();

            return PartialView(events);
        }

        public PartialViewResult Blocks(int eventID)
        {
            var blocks = _service.GetBlocks(eventID);

            return PartialView(blocks);
        }

        public PartialViewResult Genres(int eventID)
        {
            var genre = _service.GetGenres(eventID);

            return PartialView(genre);
        }

        public PartialViewResult FilmsB(int id)
        {
            string genre = null;
            int eventID = 0;
            var films = _service.GetFilms(id, genre, eventID);

            return PartialView(films);
        }

        public PartialViewResult FilmsG(string genre, int eventID)
        {
            int id = -1;
            var films = _service.GetFilms(id, genre, eventID);

            return PartialView(films);
        }

        public PartialViewResult GraphB(int id, int eventID)
        {
            string genre = null;
            var films = _service.GetGraph(id, genre, eventID);

            return PartialView(films);
        }

        public PartialViewResult GraphG(string genre, int eventID)
        {
            int id = -1;
            var films = _service.GetGraph(id, genre, eventID);

            return PartialView(films);
        }

        public PartialViewResult FilmInfo(int filmID)
        {
            var filmInfo = _service.GetFilmInfo(filmID);

            return PartialView(filmInfo);
        }


        public ActionResult LeaderBoards()
        {

            return View();
        }

        public PartialViewResult Update(int EventID)
        {
            var LeaderBoardInfo = _service.LeaderBoards(EventID);

            return PartialView(LeaderBoardInfo);
        }

        public ActionResult Demographics()
        {
            var events = _service.GetEvents();

            return View(events);
        }

        public PartialViewResult getIncome(int eventID)
        {
            var income = _service.GetIncomeChart(eventID);

            return PartialView(income);
        }

        public PartialViewResult getAge(int eventID)
        {
            var age = _service.GetAgeChart(eventID);

            return PartialView(age);
        }

        public PartialViewResult getEducation(int eventID)
        {
            var education = _service.GetEducationChart(eventID);

            return PartialView(education);
        }

        public PartialViewResult getEthnicity(int eventID)
        {
            var ethnicity = _service.GetEthnicityChart(eventID);

            return PartialView(ethnicity);
        }

        public ActionResult GenerateVoters()
        {
            return View();
        }

        
        public void genVoters(int numOfVoters)
        {
            var voters = _service.GetVoters();

            _service.CreateVoters(numOfVoters, voters);
        }
    }
}

WAFF.WebUI/Views/Reports/Blocks.cshtml
@model IEnumerable<WAFF.DataAccess.ViewModels.Voting_Data.blockVD>

@{
    var first = 0;

    foreach (var block in Model)
    {
        @Ajax.ActionLink("Block " + block.BlockID + ": " + block.BlockStart, "FilmsB", "Reports",
            new
            {
                id = block.BlockID,
                eventID = block.EventID
            },
            new AjaxOptions
            {
                UpdateTargetId = "containerFilms",
                OnSuccess = "selectedBlock(" + block.BlockID + ")"
            },
            new { id = "block" + block.BlockID})
        <br />

        if (first == 0)
        {
            <input id="currentBlock" type="hidden" value="@block.BlockID" />
            first++;
        }

        <div style="display:none">
            @Ajax.ActionLink("GraphB", "GraphB", "Reports",
            new
            {
                id = block.BlockID,
                eventID = block.EventID
            },
            new AjaxOptions
            {
                UpdateTargetId = "piechartData",
                OnSuccess = "drawChart()"
            },
            new { id = "GraphB" + block.BlockID })
        </div>
    }
}

WAFF.WebUI/Views/Reports/Demographics.cshtml
@{
    ViewBag.Title = "Demographics";
}

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript" src="~/Scripts/Demographics/Demographics.js"></script>
<script type="text/javascript" src="~/Scripts/Demographics/pieCharts.js"></script>

<h1>Demographics</h1>
<div id="EventSelect">@Html.Action("EventSelect", "Reports")</div>
<hr />
<div style ="display:inline-block; width:100%;">
    <div class="demoGraphs">
        <h2>Age</h2>
        <h5 id="ageTotal" style="padding-bottom: 10px"></h5>
        <div id="demoAge"></div>
    </div>
    <div class="demoGraphs">
        <h2>Ethnicity</h2>
        <h5 id="ethnicityTotal" style="padding-bottom: 10px"></h5>
        <div id="demoEthnicity"></div>
    </div>
    <div class="demoGraphs">
        <h2>Education</h2>
        <h5 id="educationTotal" style="padding-bottom: 10px"></h5>
        <div id="demoEducation"></div>
    </div>
    <div class="demoGraphs">
        <h2>Income</h2>
        <h5 id="incomeTotal" style="padding-bottom: 10px"></h5>
        <div id="demoIncome"></div>
    </div>
</div>

<div style="display:none" id="demoAgeInfo"></div>
<div style="display:none" id="demoEthnicityInfo"></div>
<div style="display:none" id="demoEducationInfo"></div>
<div style="display:none" id="demoIncomeInfo"></div>

<div id="initialEvent" style="display:none">
    @{
        foreach (var Event in Model)
        {
            @Ajax.ActionLink("Income", "getIncome", "Reports",
            new
            {
                eventID = Event.EventID
            },
            new AjaxOptions
            {
                UpdateTargetId = "demoIncomeInfo",
                OnSuccess = "drawChartIncome()"
            },
            new { id = "Income" + Event.EventID })

            @Ajax.ActionLink("Age", "getAge", "Reports",
            new
            {
                eventID = Event.EventID
            },
            new AjaxOptions
            {
                UpdateTargetId = "demoAgeInfo",
                OnSuccess = "drawChartAge()"
            },
            new { id = "Age" + Event.EventID })

            @Ajax.ActionLink("Education", "getEducation", "Reports",
            new
            {
                eventID = Event.EventID
            },
            new AjaxOptions
            {
                UpdateTargetId = "demoEducationInfo",
                OnSuccess = "drawChartEducation()"
            },
            new { id = "Education" + Event.EventID })

            @Ajax.ActionLink("Ethnicity", "getEthnicity", "Reports",
            new
            {
                eventID = Event.EventID
            },
            new AjaxOptions
            {
                UpdateTargetId = "demoEthnicityInfo",
                OnSuccess = "drawChartEthnicity()"
            },
                 new { id = "Ethnicity" + Event.EventID })
        }
    }
</div>

WAFF.WebUI/Views/Reports/EventLB.cshtml
@model IEnumerable<WAFF.DataAccess.ViewModels.eventDate>

<div style="display: none">
    @{
        foreach (var Event in Model)
        {
            
            @Ajax.ActionLink("update", "Update", "Reports",
            new
            {
                EventID = Event.EventID
            },
            new AjaxOptions
            {
                UpdateTargetId = "leaderBoardContainer"
            },
            new { id = "Event" + Event.EventID })
        }
    }
</div>

WAFF.WebUI/Views/Reports/FilmInfo.cshtml
@model IEnumerable<WAFF.DataAccess.ViewModels.Voting_Data.filmInfoVD>

@{
    var film = Model.First();
    <hr />
    <div style="width: 20%; display: inline-block"><p style="font-size: 18px;"><em>Film:</em></p></div>
    <div style="width: 70%; display: inline-block"><p>@film.FilmName</p></div>
    <br />

    <div style="width: 20%; display: inline-block"><p style="font-size: 18px;"><em>Genre:</em></p></div>
    <div style="width: 70%; display: inline-block"><p>@film.FilmGenre</p></div>
    <br />

    <div style="width: 20%; display: inline-block"><p style="font-size: 18px;"><em>Description:</em></p></div>
    <div style="width: 70%; display: inline-block"><p>@film.FilmDesc</p></div>
    <br />

    <div style="width: 20%; display: inline-block"><p style="font-size: 18px;"><em>Length:</em></p></div>
    <div style="width: 70%; display: inline-block"><p>@film.FilmLength Minutes</p></div>
    <br />

    <div style="width: 20%; display: inline-block"><p style="font-size: 18px;"><em>Total Votes:</em></p></div>
    <div style="width: 70%; display: inline-block"><p id="filmTotal"></p></div>
    <br />
    
    if (film.ArtistFName != null)
    { 
        <h3 style="text-align: center">Artists</h3>

        foreach (var f in Model)
        {
            <hr />
            <div style="width: 20%; display: inline-block"><p style="font-size: 18px;"><em>Name:</em></p></div>
            <div style="width: 70%; display: inline-block"><p>@film.ArtistFName @f.ArtistLname</p></div>
            <br /><br />

            <div style="width: 20%; display: inline-block"><p style="font-size: 18px;"><em>Company:</em></p></div>
            <div style="width: 70%; display: inline-block"><p>@film.ArtistCompany</p></div>
            <br /><br />

            <div style="width: 20%; display: inline-block"><p style="font-size: 18px;"><em>Email:</em></p></div>
            <div style="width: 30%; display: inline-block"><p>@film.ArtistEmail</p></div>

            <div style="width: 20%; display: inline-block"><p style="font-size: 18px;"><em>Phone:</em></p></div>
            <div style="width: 30%; display: inline-block"><p>@film.ArtistPhone</p></div>
            <br />

            <div style="width: 20%; display: inline-block"><p style="font-size: 18px;"><em>Address:</em></p></div>
            <div style="width: 30%; display: inline-block"><p>@film.ArtistAddress</p></div>

            <div style="width: 20%; display: inline-block"><p style="font-size: 18px;"><em>City:</em></p></div>
            <div style="width: 30%; display: inline-block"><p>@film.ArtistCity</p></div>
            <br />

            <div style="width: 20%; display: inline-block"><p style="font-size: 18px;"><em>State:</em></p></div>
            <div style="width: 30%; display: inline-block"><p>@film.ArtistState</p></div>

            <div style="width: 20%; display: inline-block"><p style="font-size: 18px;"><em>Zip:</em></p></div>
            if (film.ArtistZip != 0)
            {
                <div style="width: 30%; display: inline-block"><p>@film.ArtistZip</p></div>
            }
            else
            {
                <div style="width: 30%; display: inline-block"><p></p></div>
            }
        }
    }
}

WAFF.WebUI/Views/Reports/FilmsB.cshtml
@model IEnumerable<WAFF.DataAccess.ViewModels.Voting_Data.filmsVD>

@{
    var first = 0;

    foreach (var film in Model)
    {
        @Ajax.ActionLink(film.FilmName, "FilmInfo", "Reports",
        new
        {
            filmID = film.FilmID
        },
        new AjaxOptions
        {
            UpdateTargetId = "containerFilmInfo",
            OnSuccess = "selectedFilm(" + film.FilmID + ")"
        },
        new { id = "film" + film.FilmID })
        <br />

        if (first == 0)
        {
            <input id="currentFilm" type="hidden" value="@film.FilmID" />
            first++;
        }
    }
}

WAFF.WebUI/Views/Reports/FilmsBAsync.cshtml
@model IEnumerable<WAFF.DataAccess.ViewModels.filmsVD>

@foreach (var film in Model)
{

    @Ajax.ActionLink(film.FilmName, "FilmInfo", "Reports",
    new AjaxOptions
    {
        UpdateTargetId = "containerFilms"
    },
    new { id = "film" + film.FilmID })
    <br />
}

WAFF.WebUI/Views/Reports/FilmsG.cshtml
@model IEnumerable<WAFF.DataAccess.ViewModels.Voting_Data.filmsVD>

@{
    var first = 0;

    foreach (var film in Model)
    {
        @Ajax.ActionLink(film.FilmName, "FilmInfo", "Reports",
        new
        {
            filmID = film.FilmID 
        },
        new AjaxOptions
        {
            UpdateTargetId = "containerFilmInfo",
            OnSuccess = "selectedFilm(" + film.FilmID + ")"
        },
        new { id = "film" + film.FilmID })
        <br />

        if (first == 0)
        {
            <input id="currentFilm" type="hidden" value="@film.FilmID" />
            first++;
        }
    }
}

WAFF.WebUI/Views/Reports/GraphB.cshtml
@model IEnumerable<WAFF.DataAccess.ViewModels.Voting_Data.graphVD>

@{
    int count = 0;
    int total = 0;
    
    foreach (var block in Model)
    {
        <input type="hidden" id="@("FilmID" + count)" value="@block.FilmID" />
        <input type="hidden" id="@("FilmName" + count)" value="@block.FIlmName" />
        <input type="hidden" id="@("FilmVotes" + count)" value="@block.FilmVotes" />
        <input type="hidden" id="@("FilmInfoVotes" + block.FilmID)" value="@block.FilmVotes" />
    
        total = total + @block.FilmVotes;
        count++;
    }

    <input type="hidden" id="maxGraphCount" value="@count" />
    <input type="hidden" id="graphTotalVotes" value="@total" />
}

WAFF.WebUI/Views/Reports/GraphG.cshtml
@model IEnumerable<WAFF.DataAccess.ViewModels.Voting_Data.graphVD>

@{
    int count = 0;
    int total = 0;

    foreach (var graph in Model)
    {
        <input type="hidden" id="@("FilmID" + count)" value="@graph.FilmID" />
        <input type="hidden" id="@("FilmName" + count)" value="@graph.FIlmName" />
        <input type="hidden" id="@("FilmVotes" + count)" value="@graph.FilmVotes" />

        total = total + @graph.FilmVotes;
        count++;
    }
    
    <input type="hidden" id="maxGraphCount" value="@count" />
    <input type="hidden" id="graphTotalVotes" value="@total" />
}

WAFF.WebUI/Views/Reports/LeaderBoards.cshtml
@{
    ViewBag.Title = "Leader Board";
}

<script src="~/Scripts/LeaderBoards/LeaderBoardsFullScreen.js"></script>
<script src="~/Scripts/LeaderBoards/updateLeaderBoards.js"></script>

<div id="fullScreen">
    <h2 id="lbHeader">Leader Board</h2>

    <div id="lbImgHeader" style="display: none">
        <img src="~/Content/Images/girl and film.png" style="padding:20px; display: inline" , alt=" world arts film festival logo and link to home page" />
        <h2 style="padding-top: 35px; display: inline">Leader Board</h2>
    </div>

    <div style="display: none">
        <!-- Ajax.Actionlink(linktext, actionName,
                routeValues, ajaxOptions, htmlAttributes) -->
        @Ajax.ActionLink("EventSelect", "EventSelect", "Reports",
            new AjaxOptions
            {
                UpdateTargetId = "EventSelect"
            },
            new { id = "eventLoadSelect" })

        @Ajax.ActionLink("EventLB", "EventLB", "Reports",
            new AjaxOptions
            {
                UpdateTargetId = "EventLB",
                OnSuccess = "beginUpdate()"
            },
            new { id = "eventLoadLB" })
    </div>

    <div id="EventSelect">@Html.Action("EventSelect", "Reports")</div>
    <div id="EventLB"></div>

    <div id="leaderBoardContainer"></div>

    <input id="isFull" type="hidden" value="no">
    <div class="text-center">
        <div id="toFull" class="btn btn-default btn-lg" onclick="fullScreen(fullScreen)">Enter Fullscreen</div>
        <input id="test" type="hidden" value="0" />
    </div>

</div>

WAFF.WebUI/Views/Reports/Reports.cshtml
@{
    ViewBag.Title = "Reports";
}

@Html.Partial("Menu")

<h1 style="text-align: center">Reports</h1>

<img src="~/Content/Images/pageunderconstruction.png" class="center-block" />

WAFF.WebUI/Views/Reports/getAge.cshtml
@model IEnumerable<WAFF.DataAccess.ViewModels.Demographics.voterCount>

@{
    int count = 0;
    int total = 0;

    foreach (var age in Model)
    {
        <input type="hidden" id="@("graphAge" + count++)" value="@age.VoterCount" />
        total = total + age.VoterCount;
    }
    
    <input type="hidden" id="graphAgeTotal" value="@total" />
}

WAFF.WebUI/Views/Reports/getIncome.cshtml
@model IEnumerable<WAFF.DataAccess.ViewModels.Demographics.voterCount>

@{
    int count = 0;
    int total = 0;
    
    foreach (var income in Model)
    {
        <input type="hidden" id="@("graphIncome" + count++)" value="@income.VoterCount" />
        total = total + income.VoterCount;
    }

    <input type="hidden" id="graphIncomeTotal" value="@total" />
}

WAFF.WebUI/Views/Reports/update.cshtml
@model IEnumerable<WAFF.DataAccess.ViewModels.Leader_Boards.LeaderBoardEntry>

<table class="table">
    <thead>
        <tr>
            <th class="text-center"><h2><b>Place</b></h2></th>
            <th class="text-center"><h2><b>Name</b></h2></th>
            <th class="text-center"><h2><b>Genre</b></h2></th>
            <th class="text-center"><h2><b>Block Time</b></h2></th>
            <th class="text-center"><h2><b>Votes</b></h2></th>
        </tr>
    </thead>
    <tbody>
        @{
            var count = 0;
            decimal votePercent = 0;
            string vote;

            foreach (var f in Model)
            {
                <tr>
                    <td class="text-center">
                        @{
                            if (votePercent == f.VotePercentage)
                            {
                                count--;
                            }
                            
                            votePercent = f.VotePercentage;
                            vote = votePercent.ToString("0.00");
                            
                            switch (count)
                            {
                                case 0:
                                    <h4 style="color: gold"><i class="fa fa-trophy"></i> 1st</h4>
                                    count++;
                                    break;
                                case 1:
                                <h4 style="color: silver"><i class="fa fa-trophy"></i> 2nd</h4>
                                    count++;
                                    break;
                                case 2:
                                <h4 style="color: #cd7f32"><i class="fa fa-trophy"></i> 3rd</h4>
                                    count++;
                                    break;
                                default:
                                <h4>@(count + 1)th</h4>
                                    count++;
                                    break;
                            }
                        }
                    </td>
                    <td class="text-center"><h4>@f.FilmName</h4></td>
                    <td class="text-center"><h4>@f.FilmGenre</h4></td>
                    <td class="text-center"><h4>@f.BlockDayOfWeek @f.BlockStart to @f.BlockEnd</h4></td>
                    <td class="text-center"><h4>@vote%</h4></td>
                </tr>
            }
        }
    </tbody>
</table>